// 作文句式 / 高分表达数据（由《四六级真题作文类型与高分表达整理.md》整理，勿手改）
// 通过 <script> 标签加载，不受 file:// 下 CORS 拦截限制。
// 四六级通用，合并为单一 essay 数组，用 stage 区分类型：
//   句式：opening/viewpoint/cause/contrast/example/emphasis/importance/summary/suggestion/outlook
//   短语：tech/study/self/social/team/logic
window.ESSAY_DATA = {
  essay: [
    // ===== 开篇引入 · 引出话题/现象 =====
    { stage: 'opening', en: 'Nowadays, the issue of ... has aroused wide public concern.', cn: '如今，……问题引起了公众的广泛关注。' },
    { stage: 'opening', en: 'In recent years, ... has become increasingly prevalent in our daily life.', cn: '近年来，……在我们的日常生活中变得越来越普遍。' },
    { stage: 'opening', en: 'With the rapid development of ..., people are becoming increasingly aware of the importance of ...', cn: '随着……的快速发展，人们越来越意识到……的重要性。' },
    { stage: 'opening', en: 'There is a growing awareness that ... plays a vital role in ...', cn: '人们越来越意识到……在……中起着至关重要的作用。' },
    { stage: 'opening', en: 'When it comes to ..., people\'s opinions vary from person to person.', cn: '当谈到……时，人们的观点因人而异。' },
    { stage: 'opening', en: 'It is universally acknowledged that ... is of great significance to ...', cn: '众所周知，……对……具有重要意义。' },
    { stage: 'opening', en: 'Nowadays more and more people are beginning to realize the importance of ...', cn: '如今越来越多的人开始意识到……的重要性。' },
    // ===== 开篇引入 · 表明观点/立场 =====
    { stage: 'viewpoint', en: 'From my perspective, the advantages of ... outweigh its disadvantages.', cn: '在我看来，……的利大于弊。' },
    { stage: 'viewpoint', en: 'As far as I am concerned, I firmly hold the view that ...', cn: '就我而言，我坚定地认为……' },
    { stage: 'viewpoint', en: 'Personally, I am in favor of the idea that ...', cn: '就个人而言，我赞成……的观点。' },
    { stage: 'viewpoint', en: 'There is no denying that ..., but we should not overlook the fact that ...', cn: '不可否认……，但我们不应忽视……的事实。' },
    { stage: 'viewpoint', en: 'While it is true that ..., it doesn\'t mean that ...', cn: '虽然……是事实，但这并不意味着……' },
    // ===== 主体论证 · 因果关系 =====
    { stage: 'cause', en: 'This phenomenon can be mainly attributed to the following reasons.', cn: '这一现象主要可以归因于以下原因。' },
    { stage: 'cause', en: 'There are several factors that contribute to this trend.', cn: '有几个因素促成了这一趋势。' },
    { stage: 'cause', en: 'One of the primary causes is that ...', cn: '主要原因之一是……' },
    { stage: 'cause', en: 'As a result, ... has become increasingly prevalent in modern society.', cn: '因此，……在现代社会变得越来越普遍。' },
    { stage: 'cause', en: 'Owing to the fact that ..., people tend to ...', cn: '由于……的事实，人们倾向于……' },
    { stage: 'cause', en: 'The reason why ... is that ...', cn: '……的原因是……' },
    { stage: 'cause', en: '... plays a decisive role in ...', cn: '……在……中起着决定性作用。' },
    // ===== 主体论证 · 对比/利弊分析 =====
    { stage: 'contrast', en: 'On the one hand, ... On the other hand, ...', cn: '一方面，……另一方面，……' },
    { stage: 'contrast', en: 'Just as every coin has two sides, ... also has its advantages and disadvantages.', cn: '正如每个硬币都有两面，……也有其优缺点。' },
    { stage: 'contrast', en: 'While ... brings considerable benefits, it also poses certain challenges.', cn: '虽然……带来了可观的好处，但也带来了一定的挑战。' },
    { stage: 'contrast', en: 'Compared with ..., ... is more likely to ...', cn: '与……相比，……更有可能……' },
    { stage: 'contrast', en: 'In contrast to the traditional view, modern people tend to believe that ...', cn: '与传统观点相反，现代人倾向于认为……' },
    { stage: 'contrast', en: 'The advantages of ... far outweigh its drawbacks.', cn: '……的优点远远超过其缺点。' },
    // ===== 主体论证 · 举例论证 =====
    { stage: 'example', en: 'A case in point is that ...', cn: '一个恰当的例子是……' },
    { stage: 'example', en: 'Take ... as an example. It can clearly illustrate that ...', cn: '以……为例，它可以清楚地说明……' },
    { stage: 'example', en: 'According to a recent survey, ...', cn: '根据最近的一项调查，……' },
    { stage: 'example', en: 'Numerous examples can be given, but this will suffice.', cn: '可以举出无数例子，但这个就足够了。' },
    { stage: 'example', en: '... serves as a typical example to demonstrate that ...', cn: '……是证明……的典型例子。' },
    { stage: 'example', en: 'For instance, students who ... tend to perform better in ...', cn: '例如，……的学生往往在……表现更好。' },
    // ===== 主体论证 · 递进/强调 =====
    { stage: 'emphasis', en: 'What is more serious is that ...', cn: '更严重的是……' },
    { stage: 'emphasis', en: 'More importantly, ... plays an irreplaceable role in ...', cn: '更重要的是，……在……中起着不可替代的作用。' },
    { stage: 'emphasis', en: 'It is ... that really matters in the long run.', cn: '从长远来看，……才是真正重要的。' },
    { stage: 'emphasis', en: 'Not only can ..., but it can also ...', cn: '……不仅能……，还能……' },
    { stage: 'emphasis', en: 'On top of that, ... also contributes significantly to ...', cn: '除此之外，……也对……有显著贡献。' },
    { stage: 'emphasis', en: 'It is worth noting that ...', cn: '值得注意的是……' },
    // ===== 主体论证 · 重要性阐述 =====
    { stage: 'importance', en: '... plays an important/essential/vital role in ...', cn: '……在……中扮演重要/必要/关键角色。' },
    { stage: 'importance', en: '... is of great/utmost significance to ...', cn: '……对……具有重大/极其重要的意义。' },
    { stage: 'importance', en: 'It is no exaggeration to say that ... is indispensable to ...', cn: '可以毫不夸张地说，……对……是不可或缺的。' },
    { stage: 'importance', en: 'The importance of ... cannot be overemphasized.', cn: '……的重要性再怎么强调也不为过。' },
    { stage: 'importance', en: '... serves as a cornerstone of ...', cn: '……是……的基石。' },
    { stage: 'importance', en: 'Without ..., it would be impossible for ... to ...', cn: '没有……，……就不可能……' },
    // ===== 结尾总结 · 总结观点 =====
    { stage: 'summary', en: 'In conclusion, ...', cn: '总之，……' },
    { stage: 'summary', en: 'To sum up, we can safely draw the conclusion that ...', cn: '综上所述，我们可以有把握地得出结论……' },
    { stage: 'summary', en: 'Taking all these factors into consideration, we naturally come to the conclusion that ...', cn: '考虑到所有这些因素，我们自然会得出结论……' },
    { stage: 'summary', en: 'From what has been discussed above, we may reasonably arrive at the conclusion that ...', cn: '通过以上讨论，我们可以合理地得出结论……' },
    { stage: 'summary', en: 'All in all, there is some truth in both arguments, but I think the advantages of ... outweigh its disadvantages.', cn: '总而言之，两种观点都有道理，但我认为……的利大于弊。' },
    // ===== 结尾总结 · 提出建议/措施 =====
    { stage: 'suggestion', en: 'It is high time that we took effective measures to ...', cn: '是我们采取有效措施……的时候了。' },
    { stage: 'suggestion', en: 'Only in this way can we ...', cn: '只有这样，我们才能……' },
    { stage: 'suggestion', en: 'It is, therefore, imperative that ... should be done to ...', cn: '因此，当务之急是……以……' },
    { stage: 'suggestion', en: 'Measures should be taken to ...', cn: '应该采取措施来……' },
    { stage: 'suggestion', en: 'I strongly recommend that ...', cn: '我强烈建议……' },
    { stage: 'suggestion', en: 'It would be advisable to ...', cn: '……是明智的。' },
    // ===== 结尾总结 · 展望未来 =====
    { stage: 'outlook', en: 'I am confident that with joint efforts, we will ...', cn: '我相信，通过共同努力，我们将……' },
    { stage: 'outlook', en: 'Looking ahead, we can expect that ... will continue to play a significant role in ...', cn: '展望未来，我们可以预期……将继续在……中发挥重要作用。' },
    { stage: 'outlook', en: 'It is my firm belief that ... will be improved in the near future.', cn: '我坚信……在不久的将来会得到改善。' },
    { stage: 'outlook', en: 'With ..., the future of ... looks promising.', cn: '有了……，……的未来看起来充满希望。' }
  ,
  // ===== 高分表达短语（与句式同一模块，按 stage 分类）=====
    // ===== 科技与数字素养 =====
    { stage: 'tech', en: 'use technology wisely and responsibly', cn: '明智且负责任地使用技术' },
    { stage: 'tech', en: 'improve efficiency without losing independent thinking', cn: '在不丧失独立思考的前提下提高效率' },
    { stage: 'tech', en: 'distinguish reliable information from misleading content', cn: '区分可靠信息与误导性内容' },
    { stage: 'tech', en: 'make AI a tool, not a substitute for human creativity', cn: '让AI成为工具，而非人类创造力的替代品' },
    { stage: 'tech', en: 'digital literacy and critical thinking', cn: '数字素养与批判性思维' },
    { stage: 'tech', en: 'information overload and attention span', cn: '信息过载与注意力时长' },
    { stage: 'tech', en: 'strike a balance between technology and real life', cn: '在科技与现实生活之间取得平衡' },
    { stage: 'tech', en: 'technological innovation and ethical concerns', cn: '技术创新与伦理担忧' },
    // ===== 学习能力与职业准备 =====
    { stage: 'study', en: 'keep learning new skills', cn: '持续学习新技能' },
    { stage: 'study', en: 'adapt to a fast-changing world', cn: '适应快速变化的世界' },
    { stage: 'study', en: 'combine academic knowledge with practical experience', cn: '将学术知识与实践经验相结合' },
    { stage: 'study', en: 'prepare themselves for future career challenges', cn: '为未来的职业挑战做好准备' },
    { stage: 'study', en: 'lifelong learning and personal growth', cn: '终身学习与个人成长' },
    { stage: 'study', en: 'develop problem-solving abilities', cn: '培养解决问题的能力' },
    { stage: 'study', en: 'enhance employability and competitiveness', cn: '提升就业能力与竞争力' },
    { stage: 'study', en: 'step out of the comfort zone', cn: '走出舒适区' },
    // ===== 自律、目标与心理健康 =====
    { stage: 'self', en: 'turn plans into real actions', cn: '将计划转化为实际行动' },
    { stage: 'self', en: 'make steady progress step by step', cn: '一步一步稳步前进' },
    { stage: 'self', en: 'deal with pressure and setbacks', cn: '应对压力与挫折' },
    { stage: 'self', en: 'maintain a healthy balance between study and life', cn: '在学习与生活之间保持健康平衡' },
    { stage: 'self', en: 'set realistic goals and manage time effectively', cn: '设定现实目标并有效管理时间' },
    { stage: 'self', en: 'cultivate mental resilience and emotional intelligence', cn: '培养心理韧性与情商' },
    { stage: 'self', en: 'practice self-discipline and delayed gratification', cn: '践行自律与延迟满足' },
    { stage: 'self', en: 'maintain a positive mindset and optimistic attitude', cn: '保持积极的心态和乐观的态度' },
    // ===== 社会实践与责任 =====
    { stage: 'social', en: 'step out of the classroom', cn: '走出课堂' },
    { stage: 'social', en: 'develop a stronger sense of social responsibility', cn: '培养更强的社会责任感' },
    { stage: 'social', en: 'realize personal value through serving others', cn: '通过服务他人实现个人价值' },
    { stage: 'social', en: 'connect personal growth with the needs of society', cn: '将个人成长与社会需求联系起来' },
    { stage: 'social', en: 'participate in volunteer work and community service', cn: '参与志愿工作与社区服务' },
    { stage: 'social', en: 'contribute to social progress and development', cn: '为社会进步与发展做贡献' },
    { stage: 'social', en: 'broaden one\'s horizons and enrich life experience', cn: '拓宽视野并丰富人生阅历' },
    // ===== 沟通合作 =====
    { stage: 'team', en: 'respect different opinions', cn: '尊重不同意见' },
    { stage: 'team', en: 'reach agreement through reasonable discussion', cn: '通过合理讨论达成一致' },
    { stage: 'team', en: 'work together toward a common goal', cn: '朝着共同目标一起努力' },
    { stage: 'team', en: 'improve efficiency and reduce misunderstanding', cn: '提高效率并减少误解' },
    { stage: 'team', en: 'foster effective communication and teamwork', cn: '培养有效沟通与团队合作' },
    { stage: 'team', en: 'build trust and mutual understanding', cn: '建立信任与相互理解' },
    { stage: 'team', en: 'enhance interpersonal skills and social competence', cn: '提升人际交往能力与社会能力' },
    // ===== 逻辑衔接短语 =====
    { stage: 'logic', en: 'Furthermore', cn: '此外，而且（递进）' },
    { stage: 'logic', en: 'Moreover', cn: '而且，此外（递进）' },
    { stage: 'logic', en: 'In addition', cn: '此外（递进）' },
    { stage: 'logic', en: 'What is more', cn: '更重要的是（递进）' },
    { stage: 'logic', en: 'On top of that', cn: '除此之外（递进）' },
    { stage: 'logic', en: 'However', cn: '然而（转折）' },
    { stage: 'logic', en: 'Nevertheless', cn: '尽管如此（转折）' },
    { stage: 'logic', en: 'On the contrary', cn: '相反（转折）' },
    { stage: 'logic', en: 'In contrast', cn: '相比之下（转折）' },
    { stage: 'logic', en: 'Therefore', cn: '因此（因果）' },
    { stage: 'logic', en: 'Consequently', cn: '因此，结果（因果）' },
    { stage: 'logic', en: 'As a result', cn: '因此（因果）' },
    { stage: 'logic', en: 'Due to', cn: '由于（因果）' },
    { stage: 'logic', en: 'For instance', cn: '例如（举例）' },
    { stage: 'logic', en: 'For example', cn: '例如（举例）' },
    { stage: 'logic', en: 'To illustrate', cn: '举例说明（举例）' },
    { stage: 'logic', en: 'In conclusion', cn: '总之（总结）' },
    { stage: 'logic', en: 'To sum up', cn: '总而言之（总结）' },
    { stage: 'logic', en: 'All in all', cn: '总的来说（总结）' },
    { stage: 'logic', en: 'In short', cn: '简而言之（总结）' },
    { stage: 'logic', en: 'Above all', cn: '最重要的是（强调）' },
    { stage: 'logic', en: 'Most importantly', cn: '最重要的是（强调）' },
    { stage: 'logic', en: 'Admittedly', cn: '诚然（让步）' },
    { stage: 'logic', en: 'Granted', cn: '诚然（让步）' },
    { stage: 'logic', en: 'Despite', cn: '尽管（让步）' },
    { stage: 'logic', en: 'Even though', cn: '即使，尽管（让步）' }
  ]
};
